# Test-only: link apptraverse_noninteractive_test_runtime so EnableNoninteractiveCrt()
# runs before main in every Windows test executable.

if(NOT TARGET apptraverse)
  message(FATAL_ERROR "apptraverse_noninteractive_test_runtime requires apptraverse")
endif()

if(NOT DEFINED APPTRAVERSE_REPO_ROOT)
  get_filename_component(APPTRAVERSE_REPO_ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
endif()

set(_APPTRAVERSE_NONINTERACTIVE_TEST_STARTUP
  "${APPTRAVERSE_REPO_ROOT}/tests/noninteractive_test_startup.cpp")

function(apptraverse_attach_noninteractive_test_runtime target)
  if(NOT WIN32)
    return()
  endif()
  if(NOT TARGET "${target}")
    return()
  endif()
  get_target_property(_type "${target}" TYPE)
  if(NOT _type STREQUAL "EXECUTABLE")
    return()
  endif()
  get_target_property(_startup_sources "${target}" SOURCES)
  if(_startup_sources)
    list(FIND _startup_sources "${_APPTRAVERSE_NONINTERACTIVE_TEST_STARTUP}" _startup_idx)
    if(_startup_idx EQUAL -1)
      target_sources("${target}" PRIVATE "${_APPTRAVERSE_NONINTERACTIVE_TEST_STARTUP}")
    endif()
  else()
    target_sources("${target}" PRIVATE "${_APPTRAVERSE_NONINTERACTIVE_TEST_STARTUP}")
  endif()
  target_include_directories("${target}" PRIVATE "${APPTRAVERSE_REPO_ROOT}/include")
  target_link_libraries("${target}" PRIVATE apptraverse)
endfunction()

function(apptraverse_add_test_executable target)
  cmake_parse_arguments(_AT "" "" "SOURCES" ${ARGN})
  if(NOT _AT_SOURCES)
    message(FATAL_ERROR "apptraverse_add_test_executable requires SOURCES")
  endif()
  add_executable("${target}" ${_AT_SOURCES})
  target_link_libraries("${target}" PRIVATE apptraverse)
  apptraverse_attach_noninteractive_test_runtime("${target}")
endfunction()
